DROP DATABASE IF EXISTS STAGE CASCADE;
DROP DATABASE IF EXISTS MAIN  CASCADE;
DROP DATABASE IF EXISTS AGGR  CASCADE;
DROP DATABASE IF EXISTS AUDIT CASCADE;
DROP DATABASE IF EXISTS TEMP  CASCADE;
DROP DATABASE IF EXISTS VIEWS  CASCADE;

CREATE DATABASE STAGE ;
CREATE DATABASE MAIN  ;
CREATE DATABASE AGGR  ;
CREATE DATABASE AUDIT ;
CREATE DATABASE TEMP  ;
CREATE DATABASE VIEWS ;

